import Vue from 'vue'
import Router from 'vue-router'
// import Layout from "@/views/Layout/layout.vue"
Vue.use(Router)

export default new Router({
  routes: [
    {
      path:"/yaodetail",
      name:"yaodetail",
      component:()=>import("@/views/Yao/detail.vue"),
      meta:{
        title:"登录"
      }
    },
    {
      path:"/yaodetail2",
      name:"yaodetail2",
      component:()=>import("@/views/Yao/detail2.vue"),
      meta:{
        title:"登录"
      }
    },
    {
      path:"/yaodetail3",
      name:"yaodetail3",
      component:()=>import("@/views/Yao/detail3.vue"),
      meta:{
        title:"登录"
      }
    },
    {
      path:"/yaodetail4",
      name:"yaodetail4",
      component:()=>import("@/views/Yao/detail4.vue"),
      meta:{
        title:"登录"
      }
    },
    {
      path:"/",
      name:"login",
      component:()=>import("@/views/Login/login.vue"),
      meta:{
        title:"登录"
      }
    },
    {
      path: '/layout',
      name: 'layout',
      component: ()=>import("@/views/Layout/layout.vue"),
      redirect:"/layout/home",    
      children:[
        {
          path:"/home",
          name:"home",
          component:()=>import("@/views/Home/home.vue"),
          meta:{
            title:"首页"
          }
        },
        {
          path:"userList",
          name:"userList",
          component:()=>import("@/views/User/userList.vue"),
          meta:{
            title:"用户列表"
          }
        },
        {
          path:"addUser",
          name:"addUser",
          component:()=>import("@/views/User/addUser.vue"),
          meta:{
            title:"添加用户"
          }
        },
        {
          path:"UserDetail",
          name:"UserDetail",
          component:()=>import("@/views/User/addUser.vue"),
          meta:{
            title:"用户详情"
          }
        },
        {
          path:"editUser",
          name:"editUser",
          component:()=>import("@/views/User/addUser.vue"),
          meta:{
            title:"编辑用户"
          }
        },
        {
          path:"changePassword",
          name:"changePassword",
          component:()=>import("@/views/User/changePassword.vue"),
          meta:{
            title:"修改密码"
          }
        },
        {
          path:"editUserInfo",
          name:"editUserInfo",
          component:()=>import("@/views/User/editUserInfo.vue"),
          meta:{
            title:"修改个人信息"
          }
        },
        {
          path:"swiperList",
          name:"swiperList",
          component:()=>import("@/views/Swiper/swiperList.vue"),
          meta:{
            title:"轮播图列表"
          }
        },
        {
          path:"addSwiper",
          name:"addSwiper",
          component:()=>import("@/views/Swiper/addSwiper.vue"),
          meta:{
            title:"添加轮播图"
          }
        },
        {
          path:"editSwiper",
          name:"editSwiper",
          component:()=>import("@/views/Swiper/addSwiper.vue"),
          meta:{
            title:"修改轮播图"
          }
        },
        {
          path:"bookList",
          name:"bookList",
          component:()=>import("@/views/Book/bookList.vue"),
          meta:{
            title:"图书列表"
          }
        },
        {
          path:"addBook",
          name:"addBook",
          component:()=>import("@/views/Book/addBook.vue"),
          meta:{
            title:"添加图书"
          }
        },
        {
          path:"editBook",
          name:"editBook",
          component:()=>import("@/views/Book/editBook.vue"),
          meta:{
            title:"修改图书"
          }
        },
        {
          path:"category",
          name:"category",
          component:()=>import("@/views/Category/category.vue"),
          meta:{
            title:"分类列表"
          }
        },
        {
          path:"addCategory",
          name:"addCategory",
          component:()=>import("@/views/Category/addCategory.vue"),
          meta:{
            title:"添加分类"
          }
        },
      ]
    }
  ]
})
